version: "3"

services:
  node:
    container_name: astro-static-node__container
    image: node:lts-slim
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: "./project"
        target: "/var/www/html"
    working_dir: "/var/www/html"
